/** Power curve declarations.
 *
 * This file is auto generated by serialization_tool.py
 * 2025-06-06
 *
 * Do not modify.
 *
 * It contains the power curves for different engine types
 * created from power.svg.
 *
 * The power are scaled to max RPM and max power.
 *
 * @file
 */

#ifndef _RC_POWER_CURVES_H_
#define _RC_POWER_CURVES_H_

#include "curve.h"

namespace rcEngine {

/** Power curve definition for Tesla Roadster.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<4> powerCurveElectric;

/** Power curve definition for BMW 3l twin-turbo.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<6> powerCurvePetrolTwinTurbo;

/** Power curve definition for Yanmar 6LY 400 HP Marine Diesel.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<7> powerCurveDiesel;

/** Power curve definition for Porsche 911 ca 1980.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<8> powerCurvePetrol;

/** Power curve definition for Ecoboost 50HP.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<7> powerCurvePetrolTurbo;

/** Power curve definition for Motor braking power.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<5> powerCurveMotorBrake;

/** Power curve definition for invented steam engine.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<5> powerCurveSteam;

/** Power curve definition for Invented jet turbine torque.
 *
 * Used by ProcSimpleEngine.
 */
extern const rcProc::Curve<5> powerCurveTurbine;


} // namespace

#endif // _RC_POWER_CURVES_H_

