/** Signal type definition.
 *
 * This file is auto generated by signals_tool.py
 * 2025-05-24
 *
 * Do not modify.
 *
 * @file
 */

#ifndef _RC_SIGNAL_TYPESS_H_
#define _RC_SIGNAL_TYPESS_H_

#include <cstdint>

namespace rcSignals {

/** This struct contains the indices into the *Signals* structure.
 *
 *  These signals represent the main communication bus throught the
 *  project.
 *  Every 20ms the signals are set to RCSIGNAL_INVALID and then
 *  filled via input and proc-modules.
 *
 */
enum class SignalType : uint8_t {
    ST_NONE = 0,

    // -- General signals
    ST_YAW,
    ST_THROTTLE,
    ST_THROTTLE_RIGHT,
    ST_THROTTLE_LEFT,
    ST_ROLL,
    ST_PITCH,
    ST_SPEED,
    ST_AUX1,
    ST_AUX2,
    ST_IGNITION,
    ST_BRAKE,
    ST_PARKING_BRAKE,
    ST_GEAR,
    ST_TRAILER_SWITCH,
    ST_VCC,
    ST_TEMP1,
    ST_TEMP2,

    // -- Engine Simulation
    ST_ENGINE_LOAD,
    ST_RPM,

    // -- Lights
    ST_LI_INDICATOR_LEFT,
    ST_LI_INDICATOR_RIGHT,
    ST_LI_HAZARD,
    ST_FOG,
    ST_CABIN,
    ST_ROOF,
    ST_BEACON,
    ST_BEACON1,
    ST_BEACON2,
    ST_SIDE,
    ST_HIGHBEAM,
    ST_LOWBEAM,
    ST_TAIL,
    ST_INDICATOR_LEFT,
    ST_INDICATOR_RIGHT,
    ST_REVERSING,
    ST_SHAKER,

    // -- Sound output
    ST_MASTER_VOLUME,
    ST_HORN,
    ST_SIREN,
    ST_SHIFTING,
    ST_GUN,
    ST_FAN,
    ST_TURBO,
    ST_HYDRAULIC,
    ST_TRACK_RATTLE,
    ST_BUCKET_RATTLE,
    ST_TIRES,
    ST_FUEL_EMPTY,

    // -- Servo outputs
    ST_WINCH,
    ST_COUPLER,

    // -- Excavator
    ST_EX_BUCKET,
    ST_EX_DIPPER,
    ST_EX_BOOM,
    ST_EX_SWING,
    ST_NUM                 ///< total amount of types.
};

} // namespace

#endif // _RC_SIGNAL_TYPESS_H_

